name: Documentation

on:
  push:
    branches:
      - patch-2

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      charts: ${{ steps.filter.outputs.charts }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            docs:
              - 'docs/**/*'

  docs:
    name: Update
    runs-on: ubuntu-latest
    needs:
      - changes

    steps:

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Deploy
        uses: ./.github/actions/mkdocs
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
